sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.header.title_block.actions.list':
            resend_digital_download_email:
                template: '@SyliusDigitalProductPlugin/admin/order/show/content/header/title_block/actions/list/resend_digital_download_email.html.twig'
                priority: -10
